"""initial migration

Revision ID: 6e0edc2dd077
Revises: 
Create Date: 2026-05-31 15:15:32.904218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e0edc2dd077'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('user_role', postgresql.ENUM('applicant', 'employer', 'recruiter', name='user_roles'), server_default='applicant', nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_users')),
    sa.UniqueConstraint('user_login', name=op.f('uq_users_user_login'))
    )
    op.create_table('interview_slots',
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('slot_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.user_id'], name=op.f('fk_interview_slots_employer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('slot_id', name=op.f('pk_interview_slots'))
    )
    op.create_table('notifications',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='False', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_table('resumes',
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('applicant_id', sa.Integer(), nullable=False),
    sa.Column('desired_position', sa.String(length=255), nullable=False),
    sa.Column('desired_salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('experience_years', sa.Integer(), server_default='0', nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['applicant_id'], ['users.user_id'], name=op.f('fk_resumes_applicant_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resume_id', name=op.f('pk_resumes'))
    )
    op.create_table('vacancies',
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['users.user_id'], name=op.f('fk_vacancies_employer_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vacancy_id', name=op.f('pk_vacancies'))
    )
    op.create_table('matches',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('vacancy_id', sa.Integer(), nullable=True),
    sa.Column('recruiter_id', sa.Integer(), nullable=False),
    sa.Column('match_status', postgresql.ENUM('created', 'approved', 'rejected', 'scheduled', 'completed', name='match_statuses'), server_default='created', nullable=False),
    sa.ForeignKeyConstraint(['recruiter_id'], ['users.user_id'], name=op.f('fk_matches_recruiter_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.resume_id'], name=op.f('fk_matches_resume_id_resumes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.vacancy_id'], name=op.f('fk_matches_vacancy_id_vacancies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('match_id', name=op.f('pk_matches')),
    sa.UniqueConstraint('resume_id', 'vacancy_id', name=op.f('uq_matches_resume_id'))
    )
    op.create_table('interviews',
    sa.Column('interview_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('feedback_applicant', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('feedback_employer', sa.Boolean(), server_default='false', nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], name=op.f('fk_interviews_match_id_matches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['interview_slots.slot_id'], name=op.f('fk_interviews_slot_id_interview_slots'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('interview_id', name=op.f('pk_interviews')),
    sa.UniqueConstraint('match_id', name=op.f('uq_interviews_match_id')),
    sa.UniqueConstraint('slot_id', name=op.f('uq_interviews_slot_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviews')
    op.drop_table('matches')
    op.drop_table('vacancies')
    op.drop_table('resumes')
    op.drop_table('notifications')
    op.drop_table('interview_slots')
    op.drop_table('users')
    # ### end Alembic commands ###
